### PR TITLE
Maroon-410 Unity 2021 LTS Update

### LINKED ISSUE #410: Unity 2021 LTS Update

### PR DESCRIPTION
**Pull request by michaelholly**
closes #410

### CODE REVIEW

**Comment by michaelholly** [comment]
There is an unknown build error when trying to build it with Unity 2022

=================================================================
Native Crash Reporting

Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

[Editor.log](https://github.com/GameLabGraz/Maroon/files/13646247/Editor.log)

**Comment by FlorianGlawogger** [comment]
So the good thing is that the unity-test-runner on self hosted machines issue regarding permissions has been fixed. And almost all tests now pass. The bad thing is that unfortunately not all of the playmode tests pass.

We now have 3 actions where we ran the tests:
[Run 1](https://github.com/GameLabGraz/Maroon/actions/runs/7274287736)(re-run triggered by @michaelholly )
[Run 2](https://github.com/GameLabGraz/Maroon/actions/runs/7471873016)
[Run 3](https://github.com/GameLabGraz/Maroon/actions/runs/7473579953)

What I have found out so far:
- The log is very long, but by searching the log for the keyword 'failure' you can pretty quickly find the failed tests
- The failing tests are from the `WhenClickLabCategoryExperimentThenLoadScene` test type. (i.e. the test that tests the menu navigation from the main menu to the experiment)
- For all of the 3 test runs, the experiments PointWaveExperiment and TitrationExperiment failed, both because of a timeout. 
- I doubt it's a coincidence that for all 3 runs these 2 tests failed each time? But I am also not sure what those two experiments would have in common. Maybe it is just the order the tests are executed in?
- I am also not sure what could cause a timeout, as there should be no blocking calls in the test? The test just clicks on a button 3 times, waits for 1 frame after each button press, and then checks if the active scene is the according experiment...
- To attempt to get more insight, I added another test set (`StartExperimentSceneDirectly`) that attempts to load each of the experiment scenes directly (without any of the main menu navigation beforehand). But for these tests the PointWave and Titration experiments passed and only the CoulombsLaw experiment failed to load? It timeouted too after 180 seconds. (Only the third run though contains this test)
- Locally on my PC all tests pass.

Maybe I am missing something or someone else has more expertise regarding those experiments. Maybe we could try adding another `yield return null;` somewhere, hoping that that solves the problem because the build server is otherwise too slow? But debugging all this is very tedious as the builds take hours.

**Comment by FlorianGlawogger** [comment]
Seems like our problem is the "Thread Wait Time". It appears like it is larger after certain scenes, like after loading the Whiteboard scene, e.g. when loading the MainMenu after the Whiteboard it's `Thread Wait Time:       668868.875 ms`. I removed the StartExperimentsDirectlyTests again to save some time, and will look over the PR, in the future hopefully we'll figure out why the Thread Wait Time is so long, I did a quick internet search but didn't find anything regarding that for now...

**Review by FlorianGlawogger — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
