### PR TITLE
Feature/maroon 368 catalysator experiment

### PR DESCRIPTION
**Pull request by Sam-13**
Implements Langmuir Hinshelwood and Mars Van Krevelen catalysis experiment.

### CODE REVIEW

**Comment by michaelholly** [comment]
Please change your namespace to Maroon.Chemistry.Catalyst
Move the surface data into a subfolder e.g. Resources/SurfaceData
Can we reduce the UI dependencies/references in the CatalystController for the VR experiment? e.g. dropdown event listener in the inspector.
Can we also combine the different UI panels into one panel (see the other experiments)?
Do we need a real graph for the assessment graphs instead of an image, e.g. XCharts? 
Please merge the developed branch changes into your branch!

The code looks good to me.

**Comment by Sam-13** [comment]
Implemented changes suggested by you. Also added new data I got today (correct coordinates for cobalt surface and ToF for van Krevelen variant).

Not sure about the graphs, added the graphs I was told by David from the Vienna team, we can ask in the next meeting.
Will merge with develop in the coming days.

**Comment by Sam-13** [comment]
rebase on develop done

**Comment by Sam-13** [comment]
Closing as this is old, new PR can be found here: https://github.com/GameLabGraz/Maroon/pull/434.

**Pull request closed without merging**
